# Theme Colors
FUNDO = "#0F172A"        # Slate 900
PAINEL = "#1E293B"       # Slate 800
PAINEL_CARD = "#334155"  # Slate 700
BOTAO = "#2563EB"        # Blue 600
HOVER = "#22C55E"        # Green 500
ONLINE = "#22C55E"       # Green 500
OFFLINE = "#EF4444"      # Red 500
TEXTO = "#F8FAFC"        # Slate 50
TEXTO_MUTED = "#94A3B8"  # Slate 400
BORDER = "#475569"       # Slate 600

# Font Families & Sizes (using Segoe UI for a premium, clean look on Windows)
FONT_FAMILY = "Segoe UI"
TITLE_FONT = (FONT_FAMILY, 24, "bold")
SUBTITLE_FONT = (FONT_FAMILY, 14, "normal")
BUTTON_FONT = (FONT_FAMILY, 12, "bold")
CARD_TITLE_FONT = (FONT_FAMILY, 13, "bold")
CARD_TEXT_FONT = (FONT_FAMILY, 10, "normal")
STATUS_FONT = (FONT_FAMILY, 10, "normal")
FOOTER_FONT = (FONT_FAMILY, 10, "normal")
CONFIG_FONT = (FONT_FAMILY, 11, "normal")
LOG_FONT = (FONT_FAMILY, 10, "normal")

FONT_TITLE = TITLE_FONT
FONT_SUBTITLE = SUBTITLE_FONT
FONT_METRIC_VAL = (FONT_FAMILY, 22, "bold")
FONT_METRIC_LBL = (FONT_FAMILY, 10, "bold")
FONT_HEADER = (FONT_FAMILY, 11, "bold")
FONT_ROW = CARD_TEXT_FONT
FONT_BUTTON = BUTTON_FONT
FONT_LOG = (FONT_FAMILY, 10, "normal")

# Spacing
SPACING_OUTER = 20
SPACING_CARD = 15
SPACING_LABEL = 8
SPACING_INNER = 12
SPACING_SECTION = 16

# Corner Radii
RADIUS_PANEL = 12
RADIUS_CARD = 8
RADIUS_BUTTON = 6
